### ISSUE TITLE
XSS in conversations

### ISSUE THREAD

**Issue by DownGoat** [esotalk/esoTalk#108]
Found two XSS bugs.

First is in the title of a conversation, example:
The title `</title><script>alert("XSS - DownGoat - title tag")</script>` results in this: http://i.imgur.com/nXFTNFB.png

When saving a draft the conversation content is not filtered, and the content `</textarea><script>alert("XSS - DownGoat - Textarea Save Draft")</script>` results in this: http://i.imgur.com/ohR2d6Y.png

**Comment by ridzenis** [comment]
What did you write in the title of a conversation to make an alert box?
Writing <code>&lt;script>alert('1');&lt;/script></code> doesn't work for me.

Draft fix: ETConversationController.class.php:288 should be 
<code>$replyForm->setValue("content", sanitizeHTML($conversation["draft"]));</code>

P.S. code->script github bug?
<code><script>alert('test');</script></code>
should be
<code>&lt;script>alert('test');&lt;/script></code> (Used & lt ; here instead of <)

**Comment by DownGoat** [comment]
You have to escape the title tag, so adding `</title>` before what you tried should make an alert box pop up. So setting a conversation title to `</title><script>alert('1');</script>`.

I wrote this in the first post, but I'm a bit new to Github comments and it filtered out the code snippets I added to it.

**Comment by andrewks777** [comment]
DownGoat, greatly!

**Comment by andrewks777** [comment]
fix:

default.master.php:17
<title><?php echo sanitizeHTML($data["pageTitle"]); ?></title>

and to a heap
mobile.master.php:17
<title><?php echo sanitizeHTML($data["pageTitle"]); ?></title>

message.master.php:17
<title><?php echo sanitizeHTML($data["pageTitle"]); ?></title>
