### ISSUE TITLE
Form Values

### ISSUE THREAD

**Issue by alex-golubtsov** [esotalk/esoTalk#147]
My problem is in ETForm.class.php on line 283 (getValue function).
Please, return default value instead of empty string. I have quite complex form and it is important for me.
Thanks in advance.

**Comment by ekee** [comment]
I have did it like you say,But still like this,

public function getValue($field, $default = "")
{
    if ($this->isPostBack()) {

```
    // If the field is part of a multi-dimensional array (i.e. its name is like this[that][foo], we'll
    // have to parse the field's name to get the correct value from the $_POST array.
    if (strpos($field, "[") !== false) {


        $parts = explode("[", $field);
        $value = $_POST;


        // Go through each "part" in the field name and drill down into the $_POST array.
        foreach ($parts as $part) {
            $part = rtrim($part, "]");
            $value = @$value[$part];
        }


        return $value;
    }


    // If it's just a normal field name, get the value straight from POST.
    else return isset($_POST[$field]) ? $_POST[$field] : $default;
}
else
    return isset($this->values[$field]) ? $this->values[$field] : $default;
```

}

---

Beast regards.
EK

------------------ 原始邮件 ------------------
发件人: "Alex";notifications@github.com;
发送时间: 2014年1月2日(星期四) 晚上7:01
收件人: "esotalk/esoTalk"esoTalk@noreply.github.com; 

主题: [esoTalk] Form Values (#147)

My problem is in ETForm.class.php on line 283 (getValue function).
 Please, return default value instead of empty string. I have quite complex form and it is important for me.
 Thanks in advance.
