### ISSUE TITLE
members online out of sync

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#185]
I noticed the members online are sometimes out of sync. (removed the overlay for better visibility)
![screen shot 2014-04-14 at 16 48 11](https://cloud.githubusercontent.com/assets/1263414/2696557/32db7120-c3e4-11e3-9884-7f85ead1dba9.png)

**Comment by tvb** [comment]
Even better :smile:
![screen shot 2014-04-14 at 16 56 13](https://cloud.githubusercontent.com/assets/1263414/2696659/08b91608-c3e5-11e3-940c-f25ee56cd619.png)

**Comment by tobyzerner** [comment]
This is happening because the "online members" statistics is being fetched and added to the footer (in ETController::init) before the currently-logged-in user's online status is updated (in ETConversationsController::index.) It will resolve after a page refresh.

I can't think of a good way to refactor right now and it's very minor so I'll come back to it another time.

**Comment by tobyzerner** [comment]
This is too minor to worry about, closing.
