### ISSUE TITLE
scrubber indistinctness

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#190]
Wouldn't it be better to show only the months which holds posts? Now 2013 is showing more months then there are actual posts being made.
![screen shot 2014-04-16 at 13 47 42](https://cloud.githubusercontent.com/assets/1263414/2719296/91486f44-c55e-11e3-98c5-e6bf70361845.png)

**Comment by tobyzerner** [comment]
From a performance point of view, this would mean loading every post at once when viewing a conversation, so it's unfeasible. Some trickery could be done with JavaScript to hide unused months when posts have been loaded, but I don't think it's worth doing because...

I don't think the timeline works as well as I was hoping it would in practice. Particularly when there's a large number of posts in a small amount of time (i.e. within a week/month), it's pretty useless for navigating through them. I think in the future it should be replaced with a draggable scrollbar-style navigation.
