### ISSUE TITLE
Specify channels shown in the board index.

### ISSUE THREAD

**Issue by petsagouris** [esotalk/esoTalk#21]
At the moment discussions from all channels are getting on the index of the board. 
It would be nice to specify the channels from which discussions can be displayed in the index view.
(Just think of the Sandbox channel in the esotalk forums)

**Comment by tobyzerner** [comment]
When editing a channel, there's a checkbox to "Unsubscribe new users by default". I think a nice solution would be to make it so that if this box is checked, the channel will not be shown on the index of the board to guests. So guests wouldn't see it, and members wouldn't see it unless they explicitly subscribe to it. How does that sound?

**Comment by petsagouris** [comment]
I'd love more control on the hands of the administration team. But yeah I think that should match it closely.
