### ISSUE TITLE
Fontawesome Problem

### ISSUE THREAD

**Issue by felixhalim** [esotalk/esoTalk#214]
The icon won't show up.. http://forum.nusantarart.meximas.com/index.php/

**Comment by tvb** [comment]
Might have something todo with the double subdomain you are using `http://forum.nusantarart.meximas.com/`

Or with the url not being /forum/ because the source URL for the FontAwesome font is `/forum/core/skin/font/fontawesome-webfont.eot` in your code. 

It should say `/core/skin/font/fontawesome-webfont.eot`

**Comment by felixhalim** [comment]
how to solve it?

**Comment by tvb** [comment]
What is the value of `$config["esoTalk.baseURL"] = '';` in your config/config.php?
