### ISSUE TITLE
Prevent double posting

### ISSUE THREAD

**Issue by tvb** [esotalk/esoTalk#263]
We should add a mechanism that prevents double posting. I have implemented this simple mechanism before by generating a hash from the first post content and comparing it with the hash generated of the second content. During that implementation we stored every hash in the db. Should we do this here as well? Or would be storing the hash in session be enough?

**Comment by jgknight** [comment]
Do you mean not allowing one person to write what the previous person wrote?  Not sure that should be up to esoTalk core. Maybe a plugin if an admin really wants that functionality. I could see this getting in the way

**Comment by tvb** [comment]
No. Not allowing one person to post the same post previously posted.

**Comment by tvb** [comment]
No. Not allowing one person to post the same post previously posted.

**Comment by tvb** [comment]
Like so ^ :)

**Comment by jgknight** [comment]
Ah okay. This would be better implemented as a plugin since it's sort of a limited use feature (and also trivial to bypass. Add a space, change capitalization, etc.)  If somebody wants this feature it can be requested on the support forum.

Edit: forgot to add that there is already a timeout between posts so a user can't accidentally click post twice.
