### ISSUE TITLE
Sticky channels always on top for Guests

### ISSUE THREAD

**Issue by inliquid** [esotalk/esoTalk#313]
Guest always see sticky channels in converation list on top, which is not good, and not expected, since registered users do not. 
Sticky channels usually made for service purposes - forum rules, formatting, useful notes, etc. It's helpful, but this behaviours forces us not to use sticky channels much... otherwise first forum page which will be shown to the new guest will be something, but not relevant information he was looking for.

**Comment by ciruz** [comment]
For me the concept behind sticky notes is, that guests see this useful information before an registration (like the rules or where you could download what, and so on, stuff that is important) and for an active member of your community it's really not necessary to show allways the forum rules, or how you format anything, because they already know this (or they learned how to use your forum software (esotalk) and know where to find this information).

In general you are right, showing the stickys after an registration on top or until they are really read is no disadvantage. Show the stickys always on top (if already read and no new activites) is something that really annoys me in other forums, it's like we are all stupid and forget everything.

**Comment by inliquid** [comment]
Not only that, I meant let's say, if there are total 20 sticky topics (it could be), imagine if not registered user opens the forum first time what he will think about the forum seeing these 20 rules and whatsoever?

**Comment by tobyzerner** [comment]
I agree with @ciruz about the motivation for this behaviour.

@inliquid, I would argue that the order of your actions should not be (1) create 20 sticky topics, and then (2) take issue with how the behaviour breaks down given you have 20 sticky topics. Rather, you should consider the behaviour and the reasoning behind it, and then create only as many sticky topics as appropriate.
