### ISSUE TITLE
Timeline does not translate

### ISSUE THREAD

**Issue by iugo** [esotalk/esoTalk#50]
Timeline does not translate, like November... December... They are not included in the language pack.
http://img.ly/images/2605844/full

**Comment by tobyzerner** [comment]
The timeline uses PHP's date function. Using setlocale at the top of your language pack should work. http://au.php.net/manual/en/function.setlocale.php

**Comment by TomaszGasior** [comment]
No, no. 
Function setlocate() not work, because esoTalk using date() function, for example in file views/conversation/index.php in line 181:
`$name = date("F", mktime(0, 0, 0, $month, 1));`
setlocate() need function strftime().
If change in this file, in line 181 from strftime(), setlocate() work.
`$name = strftime("%B", mktime(0, 0, 0, $month, 1));`
